### ISSUE TITLE
Ignore suppressWarnInfo Version independent

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#239]
Current you specify the suppressWarnInfo per Ig, and version.

If would be nice if we could leave out the version that it applies to all ig'version.

```yaml
      suppressWarnInfo:
        hl7.fhir.r4.core#4.0.1:
          - "Constraint failed: dom-6:"
          - "regex:Entry '(.+)' isn't reachable by traversing forwards from the Composition"
        ch.fhir.ig.ch-elm#1.3.0:
          - "regex:Binding for path (.+) has no source, so can't be checked"
  ```

see also https://github.com/ahdis/ch-elm/issues/94
