### ISSUE TITLE
Unexpected validation errors when validating payload

### ISSUE THREAD

**Issue by echiu-infoway** [ahdis/matchbox#333]
I am trying to use Matchbox to validate payloads from this IG pack

https://simplifier.net/packages/ca.on.oh-ereferral-econsult/0.12.0-alpha1.0.7
for the profile: http://ehealthontario.ca/fhir/StructureDefinition/eReferralBundle
for attached json payload [OH-Bundle-Example.json](https://github.com/user-attachments/files/18428128/OH-Bundle-Example.json)

Matchbox version used: 3.9.10
Steps to reproduce:
1. Fresh database
2. include application-shared.yaml in with-ca/
```yaml
server:
  servlet:
    context-path: /matchboxv3
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: http://tx.fhir.org
      onlyOneEngine: false
      httpReadOnly: true
hapi:
  fhir:
    implementationguides:
      erec-on:
        name: ca.on.oh-eReferral-eConsult
        version: 0.12.0-alpha1.0.7

```

4. Build matchbox
5. Run using command `java -Xms1024m -Xmx24576m -Dspring.config.additional-location=file:with-ca/application-shared.yaml -jar target/matchbox.jar`
6. Validate with above payload and profile
7. See unexpected errors
![image](https://github.com/user-attachments/assets/e59d95f0-81a0-432c-95e3-6b57c125659d)

These are the validation parameters:

Validation for profile http://ehealthontario.ca/fhir/StructureDefinition/eReferralBundle|1.0.0 (null). Loaded packages: hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#4.0, hl7.terminology.r4#6.1.0, hl7.fhir.uv.extensions.r4#1.0.0, hl7.fhir.ca.baseline#1.1.7, fhir.dicom#2022.4.20221006, hl7.fhir.uv.ips#1.1.0, ca.infoway.io.psca#1.1.0, ca.infoway.io.erec#1.0.3-dft-projectathon, ca.on.oh-ereferral-econsult#0.12.0-alpha1.0.7. Duration: 2.784s. powered by matchbox 3.9.10, hapi-fhir 7.6.1 and org.hl7.fhir.core 6.5.4. Validation parameters: CliContext{doNative=false, extensions=[any], hintAboutNonMustSupport=false, recursive=false, showMessagesFromReferences=false, doDebug=false, assumeValidRestReferences=false, canDoNative=false, noExtensibleBindingMessages=false, noUnicodeBiDiControlChars=false, noInvariants=false, displayIssuesAreWarnings=true, wantInvariantsInMessages=false, doImplicitFHIRPathStringConversion=false, htmlInMarkdownCheck=WARNING, txServer='http://tx.fhir.org', txServerCache='true', txLog='null', txUseEcosystem=true, lang='null', snomedCT='null', fhirVersion='4.0.1', ig='ca.on.oh-eReferral-eConsult#0.12.0-alpha1.0.7', questionnaireMode=CHECK, level=HINTS, mode=VALIDATION, securityChecks=false, crumbTrails=false, forPublication=false, showMessageIds=false, showTerminologyRouting=false, clearTxCache=false, allowExampleUrls=true, locale='en', locations={}, jurisdiction='urn:iso:std:iso:3166#CA', igsPreloaded=null, onlyOneEngine=false, xVersion=false, httpReadOnly=true}

In my research I found this issue reporting the same error and issue is still open though I'm not sure it is related - https://github.com/hapifhir/hapi-fhir/issues/2089

some conversation here as well https://chat.fhir.org/#narrow/channel/179166-implementers/topic/Validator.20error.20-.20TYPE_SPECIFIC_CHECKS_DT_CANONICAL_RESOLVE/near/493683383

I'm not clear on how the team arrived at those errors so I'm going to double check with them.

Any help would be appreciated!
