### ISSUE TITLE
unknown extensions should not raise an error for validation (IPS)

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#394]
when we validate IPS instances there are sometimes additional extensions in the document which are onknown to the validator and this returns errors, however we think this should not be errors.

**Comment by oliveregger** [comment]
you can suppress the extensions errors the following way since v4.0.5:

```yaml
matchbox:
  fhir:
    context:
      suppressError:
        hl7.fhir.uv.ips:
          - "Type_Specific_Checks_DT_URL_Resolve@^.*extension.*url"
          - "Type_Specific_Checks_DT_URL_Resolve@^.*coding.*system"
 ```
