### ISSUE TITLE
suppress error messages for known issues

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#395]
we have in Switzerland open issue that a validation fails https://build.fhir.org/ig/hl7ch/ch-core/RelatedPerson-BiologicalFather.json.html because an extension is not in the right context. it is already noted on jira:

Editor's Comment: Extension citizenship will be allowed on RelatedPerson: https://jira.hl7.org/browse/FHIR-49948

we would like to have let allow matchbox validate ignore those errors.

same for ch-epr-term with dicom codes https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/qa.html#_scratch_repo_fsh-generated_resources_OperationDefinition-CHPDQmMatch

**Comment by oliveregger** [comment]
for AuditEvent Message are only warnings, not erros

**Comment by oliveregger** [comment]
you can add now Suppress Error messages by Ig optional version since v4.0.5:

```yaml
matchbox:
  fhir:
    context:
      suppressError:
        hl7.fhir.r4.core#4.0.1:
          - "Extension_EXTP_Context_Wrong@^RelatedPerson"
```
